In [3]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np

In [5]:
y=np.array([1,2,3,4,5,"abc"])
y
print(y.dtype)

<U11


In [6]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [7]:
a=np.array(10)
print(a)
print(a.ndim)

10
0


In [8]:
a=np.array([1,2,3])
print(a)
print("the dimention of a",a.ndim)
b=np.array([[1,2,3],[1,2,3]])
print(b)

[1 2 3]
the dimention of a 1
[[1 2 3]
 [1 2 3]]


In [9]:
print("the dimention of b",b.ndim)
c=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(c)
print("the dimention of c",c.ndim)

the dimention of b 2
[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
the dimention of c 3


In [10]:
print("the shape of a",a.shape)
print("the shape of a",b.shape)
print("the shape of a",c.shape)

the shape of a (3,)
the shape of a (2, 3)
the shape of a (1, 3, 3)


In [11]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(type(a))
print(type(b))
print(type(c))
print(len(a))
print(len(b))
print(len(c))

int32
int32
int32
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
3
2
1


In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.eye(4,dtype=int)  #we print identity matrix with 4*4 size or our wish

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [15]:
np.eye(4,3,dtype="float")

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [16]:
np.zeros((3,2),dtype="int")

array([[0, 0],
       [0, 0],
       [0, 0]])

In [17]:
np.ones((3,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [19]:
a=np.full((4,5),12,dtype=float)
print(a)

[[12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]]


In [20]:
y=(1,1,1,1)    #we print identity matrix using diag function
np.diag(y)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [21]:
y=(1,2,3,4,5,6,7,8,9)    #we print diagnoal  matrix using diag function
np.diag(y)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [22]:
x=np.arange(1,17)
print(x)
print(x.ndim)   #shows the id,0r 2d,or 3d
print(x.shape)  #shows how many rows and coloums

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1
(16,)


In [23]:
y=x.reshape(8,2)  #or y=x.reshape(8,2)
print(y)
print(y.ndim)
print(y.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
2
(8, 2)


In [27]:
z=y.reshape(4,2,2)  #or z=y.reshape(8,2,1)
print(z)
print(z.ndim)
print(z.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
3
(4, 2, 2)


In [25]:
v=z.ravel()   #we want convert any 2dim,or 3dimenstions into 1dimenstion then we can use ravel()
print(v)
print(v.ndim)
print(v.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1
(16,)
